server:
  port: 8087
  address: 0.0.0.0
  servlet:
    context-path: /


spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tcc_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&failOverReadOnly=false&autoReconnect=true
        username: root
        password: root
    application:
      name: springcloud_order

mybatis:
  type-aliases-package: org.zoo.cat.demo.springcloud.order.entity
  config-location: classpath:mybatis/mybatis-config.xml
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://eureka-test-1.idc.yst.com.cn:8080/eureka/
 instance:
   prefer-ip-address: true

#Ribbon的负载均衡策略
catOrder :
     ribbon:
        NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule
        MaxAutoRetriesNextServer : 0
feign:
  hystrix: 
     enabled : false
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        org.zoo.cat.bonuspoint: debug
        org.zoo.cat.lottery: debug
        org.zoo.cat: debug
        io.netty: info
    path: "./logs"


