server:
  port: 8087
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/tcc_order?useUnicode=true&characterEncoding=utf8
        username: root
        password: root

org:
    zoo: 
         cat: 
            serializer : kryo
            recoverDelayTime : 2
            retryMax : 30
            scheduledDelay : 2
            scheduledThreadMax :  10
            repositorySupport : db
            started: true
            async-threads: 200
            catDbConfig :
                 driverClassName  : com.mysql.jdbc.Driver
                 url :  jdbc:mysql://127.0.0.1:3306/soul-open?useUnicode=true&characterEncoding=utf8
                 username : root
                 password : root

        #repositorySupport : redis
        #tccRedisConfig:
                # masterName: mymaster
                 #sentinel : true
                 #sentinelUrl : 192.168.1.91:26379;192.168.1.92:26379;192.168.1.93:26379
                # password  : foobaredbbexONE123

mybatis:
  type-aliases-package: com.cat.tcc.demo.dubbo.order.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        org.zoo.cat.bonuspoint: info
        org.zoo.cat.lottery: info
        org.zoo.cat: info
        io.netty: info
    path: "./logs"

